### ISSUE TITLE
Croptype initialization

### ISSUE THREAD

**Issue by cenlinhe** [NCAR/noahmp#64]
https://github.com/NCAR/noahmp/blob/7ee673e88cc7a4351be329d92809a0c1ce027053/drivers/wrf/module_sf_noahmpdrv.F#L2199
@CharlesZheZhang  Do you know why only the 5th crop type fraction (i.e., CROPTYPE(I,5,J)) is used in this if-statement here? I thought it should be the total fraction of all crop types instead of just the 5th crop type here.

**Comment by CharlesZheZhang** [comment]
Hi @cenlinhe, that's what this code is doing since there are four crop types so far. The CROPTYPE variable is structured in this way: 1st layer - corn fraction, 2nd layer - soybean fraction, 3rd layer - wheat fraction, 4th layer - cotton fraction, and 5th layer - total crop fraction.

**Comment by cenlinhe** [comment]
OK, I see. Now it makes sense to me. This CROPTYPE variable is generated by WPS, right? So it will automatically compute the total fraction and assign it to the 5th layer?

**Comment by CharlesZheZhang** [comment]
Yes, that's right, the CROPTYPE variable is generated by WPS.

**Comment by cenlinhe** [comment]
OK. But I thought there are 5 crop types, at least in MPTABLE, there are 5 columns for 5 crop types?

**Comment by CharlesZheZhang** [comment]
There are five columns in the MPTABLE, but only three columns are used: corn and soybean are from Xing's paper and wheat is under review. The other two columns are not used, though are assigned by name (sorghum and rice), their parameter values are copied from the previous column. 
That's why only corn and soybean fraction from the CROPTYPE variable are used to determine the dominant crop in the noahmp_init subroutine.

**Comment by cenlinhe** [comment]
OK, I see. Thanks! I am closing this issue based on the above discussions.
